/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as SecretRoomRouteImport } from './routes/secret-room'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretRoomRoute = SecretRoomRouteImport.update({
  id: '/secret-room',
  path: '/secret-room',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/secret-room': typeof SecretRoomRoute
  '/spin': typeof SpinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/secret-room': typeof SecretRoomRoute
  '/spin': typeof SpinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/secret-room': typeof SecretRoomRoute
  '/spin': typeof SpinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/secret-room' | '/spin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/secret-room' | '/spin'
  id: '__root__' | '/' | '/admin' | '/secret-room' | '/spin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SecretRoomRoute: typeof SecretRoomRoute
  SpinRoute: typeof SpinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret-room': {
      id: '/secret-room'
      path: '/secret-room'
      fullPath: '/secret-room'
      preLoaderRoute: typeof SecretRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SecretRoomRoute: SecretRoomRoute,
  SpinRoute: SpinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
